### ISSUE TITLE
What is difference?

### ISSUE THREAD

**Issue by skyroot1022** [corazzon/KaggleStruggle#1]
Hi corazzon.
Thanks. I'm not familiar with Machine learning. It helps me a lot to learn about Machine Learning.

Let me ask one.
You used RandomForestRegressor in Lesson 3 and Lesson 4 (Youtube video).

////////////////Lesson 3:
from sklearn.ensemble import RandomForestRegressor
max_depth_list = []
model = RandomForestRegressor(n_estimators=100,
                              n_jobs=-1,
                              random_state=0) ------------------------------------(1)
%time score = cross_val_score(model, X_train, y_train, cv=k_fold, scoring=rmsle_scorer)
score = score.mean()--------------------------------------------------(4)
model.fit(X_train, y_train) ----------------------------------------------(2)
predictions = model.predict(X_test) -----------------------------------(3)
print(predictions.shape) 

//////////////////Lesson 4:
from sklearn.ensemble import RandomForestRegressor
rfModel = RandomForestRegressor(n_estimators=100) -----------------(1)
y_train_log = np.log1p(y_train) ------------------------------------------(*)
rfModel.fit(X_train, y_train_log) -----------------------------------------(2)
preds = rfModel.predict(X_train) ---------------------------------------(3)
score = rmsle(np.exp(y_train_log),np.exp(preds),False) -----------------(4)

In fact, you used the same model and algorithm in this part.
But I don't understand (*).
When I remove (*) and use y_train, the output is "non".

Could you explain about this?
Thanks.
박천.

**Comment by corazzon** [comment]
If you can read Korean, this blog post will be helpful. => http://rfriend.tistory.com/295

To avoid the error below, I use exponential and logarithmic functions.
`RuntimeWarning: divide by zero encountered in log`

I created this notebook by referring to the following kaggle kernel.
https://www.kaggle.com/viveksrinivasan/eda-ensemble-model-top-10-percentile
